### ISSUE TITLE
Not "production ready"

### ISSUE THREAD

**Issue by brmscheiner** [kesne/with-react-hooks#1]
It's missing these things:

![image](https://user-images.githubusercontent.com/9775178/53606290-30f0b200-3b6f-11e9-9bb2-1b4358ab235b.png)

...also needs 100% test coverage

**Comment by kesne** [comment]
@brmscheiner Good point! I copied the ones from React, they seemed to be pretty close to what I wanted.

Looks like the badge for React is 85% coverage. I tried to find a package with 100% coverage, but I figured if 85% is good enough for Facebook, it's probably good enough for your company too.
